### ISSUE TITLE
Problems with saving the config-file

### ISSUE THREAD

**Issue by pimpmytechno** [dmunozv04/iSponsorBlockTV#166]
I am using iSponsorBlock as an add-on for HomeAssistant.
The plugin starts successfully, but it does not work on my LG OLED C1.

My cfg file looks as follows:

> screen_id: dj************************
> name: YouTube on TV
> screen_id: ak************************
> name: YouTube on TV

In the "Options" section of the plugin, it looks like this:

```
apikey: *********************************
devices:

screen_id: dj************************
name: YouTube on TV
screen_id: dj************************
name: YouTube on TV
channel_whitelist: []
skip_categories:
sponsor
skip_count_tracking: false
mute_ads: false
skip_ads: true
```
When I try to put it into the correct format, I get an error:

_Failed to save add-on configuration, Missing option 'devices' in root in iSponsorBlockTV add-on (932a64e5_isponsorblocktv). Got {'apikey': 'myapikey', 'channel_whitelist': [], 'skip_categories': ['sponsor'], 'skip_count_tracking': False, 'mute_ads': False, 'skip_ads': True}_

Is there any solution for this problem?

- Docker on linux Arm64
- Device: LG OLED C1
- OS: WebOS FW 03.40.87
![1](https://github.com/dmunozv04/iSponsorBlockTV/assets/122159180/216f97e0-e355-4ecd-a121-db1a4a7becd2)
![2](https://github.com/dmunozv04/iSponsorBlockTV/assets/122159180/79b18ca9-bb39-44d7-8203-aca64622a548)

**Comment by dmunozv04** [comment]
This seems to be related with the home assistant add-on. I'm sure @bertybuttface can be more helpful than me debugging this issue

**Comment by bertybuttface** [comment]
I did take a look when this was posted but didn't see the root cause, apologies for not responding.

**Comment by pimpmytechno** [comment]
Do you need any additional information from me?

**Comment by bertybuttface** [comment]
No idea why its not working, here is an example config:

```
apikey: <redacted>
devices:
  - screen_id: <redacted>
    name: Device 1
  - screen_id: <redacted>
    name: Device 2
  - screen_id: <redacted>
    name: Device 3
channel_whitelist: []
skip_categories:
  - sponsor
  - selfpromo
  - exclusive_access
  - interaction
  - preview
  - filler
  - music_offtopic
  - intro
  - outro
skip_count_tracking: false
mute_ads: false
skip_ads: true
data_dir: data
```
