### ISSUE TITLE
Roku config not found

### ISSUE THREAD

**Issue by truthsword** [dmunozv04/iSponsorBlockTV#174]
Before opening an issue make sure that there are no duplicates and that you are on the latest version.
**Describe the bug**
I run the setup. Add the YT app code, exit and then the docker container... but the config isn't found.
Using Debian12 via SSH. 

**To Reproduce**
1. Run the following setup:
` docker run --rm -it -v data:/app/data --net=host -e TERM=$TERM -e COLORTERM=$COLORTERM ghcr.io/dmunozv04/isponsorblocktv --setup`
2. Select the skips and enter the Roku code from the TV app. Save. Exit.
3. Start the docker container `docker compose up`
```
services:
  iSponsorBlockTV:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: iSponsorBlockTV
    restart: unless-stopped
    volumes:
      - data:/app/data
volumes:
  data: {}
networks: {}
````
Then this:
```
docker compose up                                                 [+] Running 2/2
 ✔ Network sponsorblock_default  Created                                                     0.1s
 ✔ Container iSponsorBlockTV     Created                                                     0.1s
Attaching to iSponsorBlockTV
iSponsorBlockTV  | Could not load config file
iSponsorBlockTV  | Blank config file created
iSponsorBlockTV  | No devices found, please add at least one device
iSponsorBlockTV  | Exiting in 10 seconds...
[+] Stopping 1/1
 ✔ Container iSponsorBlockTV  Stopped                        
```
**Expected behavior**
No `Could not load config file`

**iSponsorBlockTV server (please complete the following information):**
 - OS: Docker on Debian12

Appreciate any help here. Seems so simple, yet...
